import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Leadboard",
    short_name: "Leadboard",
    description: "A focused lead pipeline for small teams.",
    start_url: "/dashboard",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    // background_color is what Android paints behind the launcher icon on
    // cold-start splash. Matching the dashboard's actual first-paint color
    // (white) makes the splash visually identical to the loaded app — no
    // dark-to-light "flash", so the launch feels instant.
    background_color: "#ffffff",
    theme_color: "#1f43e6",
    categories: ["business", "productivity"],
    icons: [
      // /icon is generated by src/app/icon.tsx (192x192 PNG).
      { src: "/icon.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon.png", sizes: "512x512", type: "image/png", purpose: "any" },
      // Maskable variant so Android can crop into its target shape without
      // chopping our logo. Using the same artwork — the 38px corner radius
      // already provides safe-area padding around the 'L' glyph.
      { src: "/icon.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: "/icon.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
