import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Leadboard",
    short_name: "Leadboard",
    description: "A focused lead pipeline for small teams.",
    start_url: "/dashboard",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#11141a",
    theme_color: "#1f43e6",
    categories: ["business", "productivity"],
    icons: [
      // /icon is generated by src/app/icon.tsx (192x192 PNG).
      { src: "/icon", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon", sizes: "512x512", type: "image/png", purpose: "any" },
      // Maskable variant so Android can crop into its target shape without
      // chopping our logo. Using the same artwork — the 38px corner radius
      // already provides safe-area padding around the 'L' glyph.
      { src: "/icon", sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: "/icon", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
